### ISSUE TITLE
Eliminar campos de la tabla usuario

### ISSUE THREAD

**Issue by wsaccaco** [ecotierraperu/issue#109]
Después de la actualización del Minka 0.1.0-Alpha3 se tiene que eliminar el campo usu_estado, usu_sistema, rol_id de la tabla usuario porque ya es obsoleto.

**Comment by lizfloresg** [comment]
También debe eliminarse la columna usu_tipo de la tabla usuario.

**Comment by lizfloresg** [comment]
La eliminación de los campos ha generado diversos problemas en SCCRP que se están corrigiendo, mayormente por la eliminación de rol_id. Se ha corregido User, LoginController, index(ambito), GrupoController, UsuarioController.
