### ISSUE TITLE
Usuarios - Corregir script de migración de usuario de Ecotierra

### ISSUE THREAD

**Issue by lizfloresg** [ecotierraperu/issue#113]
#### Descripción ####
Corregir script para migrar datos de usuario de Ecotierra a cp_usuario_cooperativa.

#### Consideraciones ####
Issue ecotierraperu/candamo#35.

**Comment by wsaccaco** [comment]
ademas tener en cuenta. Si en la tabla usuarios no tienen el correo y el rol **NO** puede ser usucop_sistema = 1, ya que no tendria sentido.
