### ISSUE TITLE
Registro de Coberturas vegetales

### ISSUE THREAD

**Issue by wsaccaco** [ecotierraperu/issue#24]
Ni bien se hace click en el registro de cobertura vegetal, desactivar el boton hasta que el sistema devuelva un resultado, ya sea success o error.. para envitar que se vuelva a registrar el mismo dato.

**Comment by lizfloresg** [comment]
No entiendo a qué se refiere este issue. Qué botón se debe desactivar?

**Comment by wsaccaco** [comment]
cuando el internet es lento da la sensación de que no pasa nada y el usuario le vuelve a dar clic y al final se guarda dos veces. Entonces lo que se tiene que hacer es que cuando le de click en el boton guardar se tiene que desahabilitar el boton hasta que el servidor de una respuesta y si es satisfactoria la respuesta se cierra el modal y actualiza el array y si es incorrecta que salga un mensaje y que vuelva a activar el boton para que intente guardar nuevamente.
