### ISSUE TITLE
Datos de registro en Productor

### ISSUE THREAD

**Issue by wsaccaco** [ecotierraperu/issue#25]
Los nombres y apellidos, dirección Establecer como capital-text. para que vea más estético.

**Comment by lizfloresg** [comment]
¿Se refiere a que los registros de productor deben lucir como las parcelas en georeferencia.index?

**Comment by lizfloresg** [comment]
Relacionado con issue #36

**Comment by wsaccaco** [comment]
https://github.com/ecotierraperu/candamo/issues/32 issue para solucionar los problemas
