### ISSUE TITLE
Actualizar el campo eliminado en georeferencia

### ISSUE THREAD

**Issue by lizfloresg** [ecotierraperu/issue#46]
#### Consideraciones ####
- [x] Actualizar Procedimientos almacenados
- [x] Agregar Campo deleted_at
- [x] Actualizar la función Remove en el controlador
- [x] generar script para actualizar los datos eliminados

**Comment by wsaccaco** [comment]
Update rows https://github.com/ecotierraperu/candamo/issues/29
