### ISSUE TITLE
Crear modulo Configuración

### ISSUE THREAD

**Issue by wsaccaco** [ecotierraperu/issue#70]
El modulo configuración va contener todos los menus de configuración del sistema para una cooperativa. Dentro del menu configuración debe aparecer un submenu, esto ayudara en su organización. 

- este menu configuración, solo puede acceder los usuarios que tienen el rol de ADMINISTRADOR
- como mínimo debe existir un administrador

**Comment by wsaccaco** [comment]
![mockup configuracion](https://cloud.githubusercontent.com/assets/5447495/10894589/965632be-817d-11e5-92dc-7835a89237c3.jpg)

**Comment by wsaccaco** [comment]
#58

**Comment by lizfloresg** [comment]
- ¿En qué consiste la opción etiquetas?

- ¿Qué se debería mostrar en permisos?

**Comment by lizfloresg** [comment]
¿Es posible eliminar a algún miembro a través del sistema?

**Comment by wsaccaco** [comment]
> ¿En qué consiste la opción etiquetas?

@lizfloresg solo es la parte de diseño, lo importante de es ese submenu y los usuarios. el submenu después lo vamos a llenar con Etiquetas ( que van a ser para identificar parcelas y/o productores ) pero todavía no es necesario, Permisos, Datos de la Cooperativa Etc. solo por a hora hay que enfocarnos en los miembros. y q el diseño sea intuitivo y bonito.

> ¿Qué se debería mostrar en permisos? ¿Puede manejarse en un modal?

primero terminemos con los usuarios o miembros

>¿Es posible eliminar a algún miembro a través del sistema?

si es posible eliminar un miembro del sistema pero solo va poder hacer los que tienen el rol de administrador.
